import '../models/area.dart';

const commandCenterDepartments = <String>[
  'ICT Division',
  'Software Engineering',
  'Multimedia',
  'Information Security',
  'Other...',
];

const commandCenterRoomNames = <String>[
  'ICT Office',
  'General Office',
  'File Room',
  'Server Room 1',
  'Access Lab',
  'Server Room 2',
  'IT Development Suite',
  'Server Room 3',
  'Network Core Operation',
];

const commandCenterFloorOptions = <String>[
  'Level G',
  'Level 1',
  'Level 2',
  'Level 3',
  'Other...',
];

final commandCenterAreas = <String, Area>{
  'ict_office': Area(
    id: 'ict_office',
    name: 'ICT Office',
    location: 'FSKTM',
    floor: 'Level 2',
    roomNumber: 'ICT-01',
    active: true,
    createdAt: DateTime(2026),
    allowedDepartments: commandCenterDepartments,
    allowedRoles: const ['User', 'Admin', 'Student', 'Staff'],
    currentOccupancy: 0,
    capacity: 24,
  ),
  'general_office': Area(
    id: 'general_office',
    name: 'General Office',
    location: 'FSKTM',
    floor: 'Level G',
    roomNumber: 'GEN-01',
    active: true,
    createdAt: DateTime(2026, 1, 2),
    allowedDepartments: commandCenterDepartments,
    allowedRoles: const ['User', 'Admin', 'Student', 'Staff'],
    currentOccupancy: 0,
    capacity: 36,
  ),
  'file_room': Area(
    id: 'file_room',
    name: 'File Room',
    location: 'FSKTM',
    floor: 'Level 3',
    roomNumber: 'FR-01',
    active: true,
    createdAt: DateTime(2026, 1, 4),
    allowedDepartments: commandCenterDepartments,
    allowedRoles: const ['Admin', 'Staff', 'User'],
    currentOccupancy: 0,
    capacity: 10,
  ),
  'server_room_1': Area(
    id: 'server_room_1',
    name: 'Server Room 1',
    location: 'FSKTM',
    floor: 'Level 1',
    roomNumber: 'SR-1',
    active: true,
    createdAt: DateTime(2026, 1, 5),
    allowedDepartments: const ['ICT Division', 'Information Security'],
    allowedRoles: const ['Admin', 'Staff', 'User'],
    currentOccupancy: 0,
    capacity: 6,
  ),
  'access_lab': Area(
    id: 'access_lab',
    name: 'Access Lab',
    location: 'FSKTM',
    floor: 'Level 3',
    roomNumber: 'AL-1',
    active: true,
    createdAt: DateTime(2026, 1, 6),
    allowedDepartments: const ['ICT Division', 'Information Security'],
    allowedRoles: const ['Admin', 'Staff', 'User'],
    currentOccupancy: 0,
    capacity: 12,
  ),
  'server_room_2': Area(
    id: 'server_room_2',
    name: 'Server Room 2',
    location: 'FSKTM',
    floor: 'Level 2',
    roomNumber: 'SR-2',
    active: true,
    createdAt: DateTime(2026, 1, 6),
    allowedDepartments: const ['ICT Division', 'Information Security'],
    allowedRoles: const ['Admin', 'Staff', 'User'],
    currentOccupancy: 0,
    capacity: 6,
  ),
  'it_development_suite': Area(
    id: 'it_development_suite',
    name: 'IT Development Suite',
    location: 'FSKTM',
    floor: 'Level 3',
    roomNumber: 'IT-2',
    active: true,
    createdAt: DateTime(2026, 1, 8),
    allowedDepartments: const ['ICT Division', 'Software Engineering'],
    allowedRoles: const ['Admin', 'Staff', 'User'],
    currentOccupancy: 0,
    capacity: 18,
  ),
  'server_room_3': Area(
    id: 'server_room_3',
    name: 'Server Room 3',
    location: 'FSKTM',
    floor: 'Level 3',
    roomNumber: 'SR-3',
    active: true,
    createdAt: DateTime(2026, 1, 7),
    allowedDepartments: const ['ICT Division', 'Information Security'],
    allowedRoles: const ['Admin', 'Staff', 'User'],
    currentOccupancy: 0,
    capacity: 6,
  ),
  'network_core_operations': Area(
    id: 'network_core_operations',
    name: 'Network Core Operation',
    location: 'FSKTM',
    floor: 'Level 3',
    roomNumber: 'NCO-3',
    active: true,
    createdAt: DateTime(2026, 1, 10),
    allowedDepartments: const ['ICT Division', 'Information Security'],
    allowedRoles: const ['Admin', 'Staff', 'User'],
    currentOccupancy: 0,
    capacity: 8,
  ),
};
